package com.multithreading;

public class WMultiTh {

	public static void main(String[] args) throws InterruptedException{
		for(int i=0;i<5;i++) {
			System.out.println("typing.....");
			Thread.sleep(1000);
		}
		for(int i=0;i<5;i++) {
			System.out.println("Sell check.....");
			Thread.sleep(1000);
		}
		for(int i=0;i<5;i++) {
			System.out.println("saving......");
			Thread.sleep(1000);
		}

	}

}

// OUTPUT 

//typing.....
//typing.....
//typing.....
//typing.....
//typing.....
//
//Sell check.....
//Sell check.....
//Sell check.....
//Sell check.....
//Sell check.....
//
//saving......
//saving......
//saving......
//saving......
//saving......
//
